name: EazyNick
version: '0.0.0'
author: Justix
main: com.justixdev.eazynick.EazyNick
description: This plugin allows you to change your identity (skin, name, uuid, nametag, tabname, chatname)
website: https://github.com/JustixDevelopment/EazyNick/
softdepend: [PlaceholderAPI, CloudNetAPI, ColoredTags, NametagEdit, PermissionsEx, LuckPerms, Datenschutz, Vault, SurvivalGames, AuthMe, TAB, DeluxeChat, ChatControl, Essentials, SkinsRestorer]
api-version: 1.13
load: POSTWORLD

permissions:
  eazynick.help:
    description: Allows you to use /eazynick
  eazynick.reload:
    description: Allows you to use /reloadconfig and /eazynick reload
  eazynick.support:
    description: Allows you to use /eazynick support
  eazynick.updatecheck:
    description: Allows you to use /nickupdatecheck
  eazynick.real:
    description: Allows you to use /realname
  eazynick.nick.random:
    description: Allows you to use /nick
  eazynick.nick.custom:
    description: Allows you to use /nick «name» + allows you to enter a name in the bookgui
  eazynick.nick.reset:
    description: Allows you to use /resetname and /unnick
  eazynick.skin.random:
    description: Allows you to use /changeskin
  eazynick.skin.custom:
    description: Allows you to use /changeskin «name»
  eazynick.skin.reset:
    description: Allows you to use  /resetskin
  eazynick.skin.fix:
    description: Allows you to use /fixskin
  eazynick.gui.classic:
    description: Allows you to use /nickgui
  eazynick.gui.list:
    description: Allows you to use /nicklist
  eazynick.gui.book:
    description: Allows you to use /bookgui
  eazynick.other.nick.random:
    description: Allows you to use /nickother «player»
  eazynick.other.nick.custom:
    description: Allows you to use /nickother «player» «name»
  eazynick.other.nick.reset:
    description: Allows you to reset another players identity using /nickother «player»
  eazynick.other.skin.random:
    description: Allows you to use /changeskinother «player»
  eazynick.other.skin.custom:
    description: Allows you to use /changeskinother «player» «name»
  eazynick.other.skin.reset:
    description: Allows you to use /resetskinother «player»
  eazynick.nickedplayers:
    description: Allows you to use /nickedplayers
  eazynick.item:
    description: Lets you receive the nick item (if enabled in setup.yml) and allows you to use /togglebungeenick
  eazynick.actionbar.other:
    description: Shows the alternate actionbar message
  eazynick.bypasslobbymode:
    description: Lets you bypass the LobbyMode
  eazynick.bypass:
    description: See every player undisguised (if enabled in setup.yml)
    default: false
