name: Release version

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/release.yml
      - .github/.version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read .version file
        id: version
        run: echo "::set-output name=version::$(cat .github/.version)"

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' pom.xml
          grep pom.xml -e ${{ steps.version.outputs.version }}
          sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' src/main/resources/plugin.yml
          grep src/main/resources/plugin.yml -e ${{ steps.version.outputs.version }}
          mkdir lib
          curl -L https://github.com/PEXPlugins/PermissionsEx/releases/download/STABLE-1.23.4/PermissionsEx-1.23.4.jar -o lib/PermissionsEx.jar
          curl -L https://api.spiget.org/v2/resources/3836/download -o lib/NametagEdit.jar
          curl -L https://cdn.getbukkit.org/spigot/spigot-1.7.10-SNAPSHOT-b1657.jar -o lib/spigot-1.7.10.jar
          curl -L https://cdn.getbukkit.org/spigot/spigot-1.8-R0.1-SNAPSHOT-latest.jar -o lib/spigot-1.8.jar
          mvn -B package --file pom.xml
          mv target/eazynick-*.jar target/EazyNick.jar

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: target/*.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          repo_token: ${{ github.token }}
          title: v${{ steps.version.outputs.version }}
          automatic_release_tag: v${{ steps.version.outputs.version }}
          files: |
            target/EazyNick.jar